@api = http://localhost:4006/usuario
@id = 218

### obtener guitarras
{{api}}/obtener-usuarios

#### crear guitarra
POST {{api}}/crear
Content-Type: application/json

{
    "nombre": "Guitarra electrica",
    "precio": 10
}

#### crear guitarra
POST {{api}}/login
Content-Type: application/json

{
    "nombre": "Guitarra electrica",
    "precio": 10
}

### actualizar guitarra 
PUT {{api}}/actualizar-guitarra
Content-Type: application/json

{
    "id": "629136dc33de1941ff49c3fa",
    "nombre": "Guitarra electrica",
    "precio": 2
}

### eliminar guitarra 
DELETE {{api}}/borrar-guitarra
Content-Type: application/json

{
    "id": "629136dc33de1941ff49c3fa"
}